### PR TITLE
Update to required versions of tools

### PR DESCRIPTION
**Pull request by kjonick1**
Update to pull in specific versions of tools used in container.  

Using the string to tag versions in Circle.ci:

PackerVer.TerraformVer.Buildnum

### CODE REVIEW

**Review by pickgr — APPROVED** [review]
Thanks Kathy - this looks good.  Just a note that we are using packer version 0.10.2 in Bamboo right now.  I just used it to build a new AMI last week.  I should have checked that.  I'm guessing there's no problem going to 0.12.0 but I'll make a note to explicitly test that.  FYI: @cristobal23

**Comment by kjonick1** [comment]
Would you rather me switch to using 0.10.2 version in container?

**Comment by pickgr** [comment]
Actually - maybe we should for now and then we can track upgrading at a later time.  Thanks!

**Comment by kjonick1** [comment]
I had to switch back to the new packer version container.  The 0.10.2 version did not have packer executables as we need them.  Let me know if you can test that.  If we need 0.10.2, then we can build that container with files we need.

**Comment by pickgr** [comment]
Hi Kathy,

This is our only build that uses packer:

https://whistle.unif.io/builds/browse/SCM-EH

I guess we're going to want to migrate this to the new container also (which may be out of the scope of your task).  Anyway, feel free to clone and run it.  **However, please note that it will publish a new AMI to Atlas and S3 which we definitely don't want to do as it will get read by our pipelines.**

I think the easiest way to disable this would be to take out the post-processor from packer/modules/ecs/aws-linux-ecs.json in the infrastructure repo (temporarily on a branch)  @blakeneyops may have another suggestion for testing?

I should also mention that the packer version in Bamboo is set via a global variable in Bamboo right now.  I guess you would figure this out pretty quickly :)

**Comment by kjonick1** [comment]
Okay, I can clone and remove final steps before testing it.  That is what I did with the Terraform build as well since I didn't want to affect any downstream processes.

**Pull request merged**
